<a href="https://colab.research.google.com/github/prudenciadofelixluigi/LinearAlgeb/blob/main/Assignment_6_Prudenciado_Midterms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#**Transposition**
One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched.

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$
$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$


This can now be achieved programmatically by using np.transpose() or using the T method.

In [2]:
A = np.array ([
     [1,2,5],
     [5,-1,0],
     [0,-3,3]         
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [3]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [4]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [5]:
np.array_equiv(AT1, AT2)

True

In [6]:
B = np.array ([
     [1, 2, 3, 5],
     [5, 2, 8, 6]           
])

B.shape

(2, 4)

In [7]:
np.transpose(B).shape

(4, 2)

In [8]:
B.T.shape

(4, 2)

In [9]:
Z=np.array([
    [3,6,9],
    [1,0,1]        
])
Z.shape

(2, 3)

In [10]:
C = np.array ([
    [ 1, 2, 3],
    [ 1, 5, 5],
    [ 1, 5, 6]           

])

C.shape

(3, 3)

In [11]:
AT3 = np.transpose(C)
AT3

array([[1, 1, 1],
       [2, 5, 5],
       [3, 5, 6]])

In [12]:
AT4 = A.T
AT4

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [13]:
np.array_equiv(AT3, AT4)

False

# **Dot Product**
If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs.

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$
The dot product will then be computed as:$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$

This could be achieved programmatically using np.dot(), np.matmul() or the @ operator.

In [14]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [15]:
np.array_equiv(X, Y)

False

In [16]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [17]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [18]:
X @ Y

array([[3, 4],
       [2, 2]])

In [19]:
D = np.array ([
    [4,5,1],
    [1,2,5],
    [7,5,1]           
])

E = np.array ([
    [1,5,8],
    [1,2,4],
    [7,9,8]          
])

In [20]:
np.dot(D,E)

array([[16, 39, 60],
       [38, 54, 56],
       [19, 54, 84]])

In [21]:
D.dot(E)

array([[16, 39, 60],
       [38, 54, 56],
       [19, 54, 84]])

In [22]:
D @ E

array([[16, 39, 60],
       [38, 54, 56],
       [19, 54, 84]])

In [23]:
np.dot(D, E)

array([[16, 39, 60],
       [38, 54, 56],
       [19, 54, 84]])

# **Rule 1: The inner dimensions of the two matrices in question must be the same.**
So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.

In [24]:
A = np.array([
    [2, 4],
    [5, -2],
    [0, 1]
])
B = np.array([
    [1,1],
    [3,3],
    [-1,-2]
])
C = np.array([
    [0,1,1],
    [1,1,2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [25]:
A @ C

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [26]:
B @ C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

In [27]:
A @ B.T

array([[  6,  18, -10],
       [  3,   9,  -1],
       [  1,   3,  -2]])

In [28]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [29]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [30]:
X @ Y.T

array([[13]])

# Rule 2: Dot Product has special properties
Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:

$$A \cdot B \neq B \cdot A$$
$$A \cdot (B \cdot C) = (A \cdot B) \cdot C$$
$$A\cdot(B+C) = A\cdot B + A\cdot C$$
$$(B+C)\cdot A = B\cdot A + C\cdot A$$
$$A\cdot I = A$$
$$A\cdot \emptyset = \emptyset$$

I'll be doing just one of the properties and I'll leave the rest to test your skills!

In [31]:
A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,1]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,4,8]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
A.dot(np.eye(3))

array([[3., 2., 1.],
       [4., 5., 1.],
       [1., 1., 1.]])

In [34]:
np.array_equal(A@B, B@A)

False

In [35]:
E = A @ (B @ C)
E

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [36]:
F = (A @ B) @ C
F

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [37]:
np.array_equal(E, X)

False

In [38]:
np.array_equiv(E, F)

True

In [39]:
A @ E

array([[455, 205, 368],
       [862, 385, 691],
       [211,  95, 172]])

In [40]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.array_equal(a_dot_z,z_mat)


True

In [43]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

#**Determinant**

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$We can compute for the determinant as:$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$So if we have $A$ as:$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using np.linalg.det().

In [44]:
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)


3.0000000000000004

In [45]:
B = np.array([
              [1, 5, 2],
              [3, -1 ,-1],
              [0, -2, 1]
])
np.linalg.det(B)

-30.000000000000014

# **Inverse**
The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$First, we need to get the determinant of $M$.$$|M| = (1)(5)-(-3)(7) = 26$$Next, we need to reform the matrix into the inverse form:$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$So that will be:$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} &\frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use np.linalg.inv().

In [46]:
M = np.array([
    [1,7],
    [-3, 5]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [47]:
P = np.array([
              [6, 9, 0],
              [4, 2, -1],
              [3, 6, 7]
])
Q = np.linalg.inv(P)
Q

array([[-0.12578616,  0.39622642,  0.05660377],
       [ 0.19496855, -0.26415094, -0.03773585],
       [-0.11320755,  0.05660377,  0.1509434 ]])

In [48]:
P @ Q

array([[ 1.00000000e+00, -5.55111512e-17, -6.93889390e-18],
       [ 8.32667268e-17,  1.00000000e+00, -2.77555756e-17],
       [ 2.77555756e-17, -1.38777878e-17,  1.00000000e+00]])

In [49]:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [50]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[0.7 ],
       [0.82],
       [0.72]])

# **Activity**
Task 1
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

# $A \cdot B \neq B \cdot A$

This property shows a commutative but as observe why does it is not equal to each other if the the commutative property states that even the numbers changes its place the sum and product are still the same? The answer is, the operation used here has different functions and way of calculations such that following the formula:

$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

In [51]:
A = np.array([
    [2,1,1],
    [6,5,2],
    [3,0,1]
])
B = np.array([
    [2,1,6],
    [4,2,9],
    [4,4,1]
])
C = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])

In [52]:
A.dot(B)

array([[12,  8, 22],
       [40, 24, 83],
       [10,  7, 19]])

In [53]:
B.dot(A)

array([[28,  7, 10],
       [47, 14, 17],
       [35, 24, 13]])

In [54]:
np.array_equal(A @ B, B @ A)

False

# $A \cdot (B \cdot C) = (A \cdot B) \cdot C$

This shows the property of associative wherein even it has three or more numbers added or multiplied the sum and product doesn't change regardless of the groupings of addends.

In [55]:
L = A.dot(B.dot(C))
L

array([[12,  8, 22],
       [40, 24, 83],
       [10,  7, 19]])

In [56]:
U = (A.dot(B)).dot(C)
U

array([[12,  8, 22],
       [40, 24, 83],
       [10,  7, 19]])

In [57]:
np.array_equal(A.dot(B.dot(C)),(A.dot(B)).dot(C))

True

# $A\cdot(B+C) = A\cdot B + A\cdot C$

This property is the same as the property below following the process of distributive property in which after adding the quantities of B and C and dotted to A the results will be the same.

In [58]:
I = A.dot(B + C)
I

array([[14,  9, 23],
       [46, 29, 85],
       [13,  7, 20]])

In [59]:
G = A.dot(B) + A.dot(C)
G

array([[14,  9, 23],
       [46, 29, 85],
       [13,  7, 20]])

In [60]:
np.array_equal(I , G)

True

In [61]:
np.array_equal(I , B)

False

# $(B+C)\cdot A = B\cdot A + C\cdot A$

In this property of matrix, distributive property can be observe in which the dimensions of A were distributed to the dimension of B and C calculating the same dimensions and elements of each side. 

In [62]:
F = (B + C).dot(A)
F

array([[30,  8, 11],
       [53, 19, 19],
       [38, 24, 14]])

In [63]:
P = B.dot(A) + C.dot(A)
P

array([[30,  8, 11],
       [53, 19, 19],
       [38, 24, 14]])

In [64]:
np.array_equal(F , P)

True

In [65]:
np.array_equal(F , G)

False

# $A\cdot I = A$

The property of this matrix uses an *I * (eye) kwown as an Identity matrix which consist only a diagonal of 1 (ones). 

In [66]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
E = A.dot(np.eye(3))
E

array([[2., 1., 1.],
       [6., 5., 2.],
       [3., 0., 1.]])

In [68]:
np.array_equal(A.dot(np.eye(3)), A)

True

In [69]:
np.array_equal(A.dot(np.eye(3)) , B)

False

In [70]:
X = A.dot(null)
X

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# $A\cdot \emptyset = \emptyset$

In this property, the dimension A was dotted to a null or known as empty set which consist of zero (0) elements. As observe in the cells, the given property was proved using the coded commands. 

In [71]:
X = A.dot(null)
X

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.array_equal(X , null)

True

# **Conclusion**

Performing this laboratory activity developed the skills I utilized from the previous activity which was solving different matrix algebra. In manual calculations of matrices it consumes a lot of time but using Python Programming, it provides convenience and ease of coding. In addition, it can be also solve through tecniques using calculator. For this, there are different ways on how to solve matrix algebra in a convenient manner such as using Python Progamming, applying shortcut teechniques in manual calculation and also the use of calculators. 